name: 'enthusiast-polymer'
version: 0.0.1
description: A web app built using polymer.dart.
author: Jakub Danek <danek.ja@gmail.com>
homepage: http://www.danekja.org

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  darthusiast:
    path: ../framework
    version: any
  browser: '>=0.10.0 <0.11.0'
  paper_elements: '>=0.7.0 <0.8.0'
  polymer: '>=0.16.0 <0.17.0'
  redstone: any
  redstone_mapper: any
  shelf_static: any



transformers:
#order matters here!
- redstone_mapper
- polymer:
    entry_points: web/index.html
