name: 'enthusiast_polymer'
version: 0.0.1
description: A web app built using polymer.dart.
author: Jakub Danek <danek.ja@gmail.com>
homepage: http://www.danekja.org

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  darthusiast:
    path: ../framework
  browser: '>=0.10.0 <0.11.0'
  polymer: '1.0.0-rc.15'
  polymer_elements: '1.0.0-rc.8'
  redstone_mapper:
    git: https://github.com/redstone-dart/redstone_mapper.git
  shelf_static: any



transformers:
#order matters here!
#- redstone_mapper
- polymer:
    entry_points: web/index.html
