name: 'enthusiast'
version: 0.0.1
description: A web app built using polymer.dart.
author: Jakub Danek <danek.ja@gmail.com>
homepage: http://www.danekja.org

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  browser: '>=0.10.0 <0.11.0'
  mongo_dart: any
  paper_elements: '>=0.7.0 <0.8.0'
  polymer: '>=0.16.0 <0.17.0'
  redstone: any
  redstone_mapper: any
  redstone_mapper_mongo: any



transformers:
- polymer:
    entry_points: web/index.html
- redstone_mapper