name: 'enthusiast-server'
version: 0.0.1
description: A web app built using polymer.dart.
author: Jakub Danek <danek.ja@gmail.com>
homepage: http://www.danekja.org

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  darthusiast:
    path: ../framework/
    version: any
  mongo_dart: any
  redstone: any
  redstone_mapper: any
  redstone_mapper_mongo: any
  shelf_static: any



transformers:
#order matters here!
- redstone_mapper
