name: 'darthusiast'
version: 0.0.1
description: Application Archetype for Dart built on top of Redstone framework.
author: Jakub Danek <danek.ja@gmail.com>
homepage: http://www.danekja.org

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  polymer: '1.0.0-rc.15'
  redstone_mapper_mongo:
    git: https://github.com/redstone-dart/redstone_mapper_mongo.git